//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RibbonApplicationOpgi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Benificiere
    {
        public int Id { get; set; }
        public string Num { get; set; }
        public Nullable<int> Id_postulant { get; set; }
        public Nullable<System.DateTime> Date_Maj { get; set; }
        public Nullable<int> Id_Projet { get; set; }
        public string Adress { get; set; }
    
        public virtual Postulant Postulant { get; set; }
        public virtual Projet Projet { get; set; }
    }
}
