//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RibbonApplicationOpgi.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FiltreEntities : DbContext
    {
        public FiltreEntities()
            : base("name=FiltreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Benificiere> Benificieres { get; set; }
        public virtual DbSet<Postulant> Postulants { get; set; }
        public virtual DbSet<Programme> Programmes { get; set; }
        public virtual DbSet<Projet> Projets { get; set; }
    }
}
