//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RibbonApplicationOpgi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postulant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Postulant()
        {
            this.Benificieres = new HashSet<Benificiere>();
        }
    
        public int Id { get; set; }
        public string Ref { get; set; }
        public string Valide { get; set; }
        public Nullable<System.DateTime> Date_Demande { get; set; }
        public Nullable<int> Id_programme { get; set; }
        public string nom { get; set; }
        public string Nom_jeune { get; set; }
        public string Prenom { get; set; }
        public string Sexe { get; set; }
        public Nullable<System.DateTime> Date_naissance { get; set; }
        public string Type_date_naissance { get; set; }
        public string Lieu_naissance { get; set; }
        public string Sit_Familliale { get; set; }
        public string Prenom_pere { get; set; }
        public string Nom_mere { get; set; }
        public string prenom_mere { get; set; }
        public string Nom_conjoint { get; set; }
        public string Prenom_Conjoint { get; set; }
        public Nullable<System.DateTime> Date_naissance_conjoint { get; set; }
        public string Type_Date_naissance_Conjoint { get; set; }
        public string Lieu_Naissance_conjoint { get; set; }
        public string Prenom_pere_conjoint { get; set; }
        public string Nom_mere_conjoint { get; set; }
        public string Prenom_mere_conjoint { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Benificiere> Benificieres { get; set; }
        public virtual Programme Programme { get; set; }
    }
}
